openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

logging:
  level:
    org.apache.pdfbox: off
spring:
  application:
    name: ai-flow
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: override
    password: override
    username: override
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
